import type { ProductRow, CustomerWithBalance, DashboardStats } from "@/lib/types/database";

/** Builds a formatted "Low Stock Report" WhatsApp message. */
export function buildLowStockReport(storeName: string, products: ProductRow[]): string {
  if (products.length === 0) {
    return `*${storeName} — Low Stock Report*\n\nAll products are above their low stock threshold. Nothing to restock right now.`;
  }

  const lines = products
    .map((p) => `• ${p.name}: ${p.quantity} ${p.unit ?? "units"} left (threshold: ${p.low_stock_threshold})`)
    .join("\n");

  return `*${storeName} — Low Stock Report*\n\n${lines}\n\n_Generated by DexLedger_`;
}

/** Builds a formatted "Outstanding Credit Report" WhatsApp message. */
export function buildOutstandingCreditReport(storeName: string, customers: CustomerWithBalance[]): string {
  const outstanding = customers.filter((c) => c.outstanding_balance > 0);

  if (outstanding.length === 0) {
    return `*${storeName} — Outstanding Credit Report*\n\nNo outstanding balances. All customer accounts are settled.`;
  }

  const total = outstanding.reduce((sum, c) => sum + c.outstanding_balance, 0);
  const lines = outstanding
    .map((c) => `• ${c.name}: ₹${c.outstanding_balance.toFixed(2)}`)
    .join("\n");

  return `*${storeName} — Outstanding Credit Report*\n\n${lines}\n\n*Total Outstanding: ₹${total.toFixed(2)}*\n\n_Generated by DexLedger_`;
}

/** Builds a formatted daily/weekly summary WhatsApp message. */
export function buildSummaryReport(
  storeName: string,
  period: "daily" | "weekly",
  stats: DashboardStats
): string {
  const periodLabel = period === "daily" ? "Daily Summary" : "Weekly Summary";

  return [
    `*${storeName} — ${periodLabel}*`,
    "",
    `Total Products: ${stats.total_products}`,
    `Low Stock Products: ${stats.low_stock_products}`,
    `Total Customers: ${stats.total_customers}`,
    `Outstanding Credit: ₹${stats.outstanding_credit.toFixed(2)}`,
    "",
    "_Generated by DexLedger_",
  ].join("\n");
}
